(if (require 'popwin nil t)
  (progn
    (setq display-buffer-function 'popwin:display-buffer)
    (setq popwin:popup-window-height 0.4)
    (setq anything-samewindow nil)
    (push '("*anything*" :height 20) popwin:special-display-config)
    (push '(dired-mode :position top) popwin:special-display-config)
    (push '("\\*[Vv][Cc]" :regexp t :position top) popwin:special-display-config)
    (push '("\\*git-" :regexp t :position top) popwin:special-display-config)
))
